-- liquibase formatted sql

-- changeset sokol:1
CREATE TABLE student (
    id BIGINT NOT NULL generated by default as identity PRIMARY KEY,
    age INTEGER NOT NULL,
    name VARCHAR(255),
    faculty_id BIGINT,
    avatar_id BIGINT
);
-- changeset sokol:2
ALTER TABLE student ADD FOREIGN KEY (faculty_id) REFERENCES faculty;
ALTER TABLE student ADD FOREIGN KEY (avatar_id) REFERENCES avatar;
--changeset sokol:3
ALTER TABLE student ADD CONSTRAINT age_constraint CHECK (age >= 16);